"use strict";

// 1. create a date object
const today = new Date();
console.log(today);

// we can generate a date object by passing a string also but not recommended
console.log(new Date("Wed Jul 23 2025 17:28:55"));
console.log(new Date("August 15 1990"));
console.log(new Date("15 Aug 1990"));
console.log(new Date("Aug 15 1990"));

const account1 = {
  owner: "Jonas Schmedtmann",
  movements: [200, 455.23, -306.5, 25000, -642.21, -133.9, 79.97, 1300],
  interestRate: 1.2, // %
  pin: 1111,

  movementsDates: [
    "2019-11-18T21:31:17.178Z",
    "2019-12-23T07:42:02.383Z",
    "2020-01-28T09:15:04.904Z",
    "2020-04-01T10:17:24.185Z",
    "2020-05-08T14:11:59.604Z",
    "2020-05-27T17:01:17.194Z",
    "2020-07-11T23:36:17.929Z",
    "2020-07-12T10:51:36.790Z",
  ],
  currency: "EUR",
  locale: "pt-PT", // de-DE
};

// if date are generated by js we can ofcourse create date objects with those strings
console.log("Movement Dates");
account1.movementsDates.forEach((date) => console.log(`\t${new Date(date)}`));

// new Date(year, month, date, hour, mins, seconds)
// month start from 0
console.log(new Date(2037, 10, 19, 15, 23, 5));
console.log("----------------------------");

console.log(typeof today, today);
console.log(typeof today.getFullYear(), today.getFullYear());
console.log(typeof today.getMonth(), today.getMonth());
console.log(typeof today.getDate(), today.getDate());
console.log(typeof today.getDay(), today.getDay());

console.log(typeof today.getHours(), today.getHours());
console.log(typeof today.getMinutes(), today.getMinutes());
console.log(typeof today.getSeconds(), today.getSeconds());

// get date formatted following international standards
console.log(today.toISOString());
console.log(today.getMilliseconds());

// getting a time stamp
console.log(today.getTime());

// getting time stamp for current moment
console.log(Date.now());
